#!/bin/sh
VERSION=$1
SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Docker login
echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

# Build base image
docker build \
    --build-arg HELM_VERSION=v3.1.2 \
    -t alphaunito/streamflow:${VERSION}-base \
    ${SCRIPT_DIRECTORY}
docker push alphaunito/streamflow:${VERSION}-base

# Tag as latest
docker tag alphaunito/streamflow:${VERSION}-base alphaunito/streamflow:latest
docker push alphaunito/streamflow:latest

# Build Helm 2 image
docker build \
    --build-arg BASE_IMAGE=alphaunito/streamflow:${VERSION}-base \
    --build-arg HELM_VERSION=v2.16.3 \
    -t alphaunito/streamflow:${VERSION}-helm2 \
    ${SCRIPT_DIRECTORY}/helm/docker/helm2
docker push alphaunito/streamflow:${VERSION}-helm2
