from os import path
from setuptools import setup

version = "0.0.4"

this_directory = path.abspath(path.dirname(__file__))
with open(path.join(this_directory, "README.md"), encoding="utf-8") as f:
    long_description = f.read()

setup(
    name="streamflow",
    version=version,
    packages=[
        "streamflow",
        "streamflow.cwl",
        "streamflow.data",
        "streamflow.config",
        "streamflow.connector",
        "streamflow.scheduling",
    ],
    package_data={"streamflow.config": ["schemas/v1.0/*.json"]},
    include_package_data=True,
    url="https://github.com/alpha-unito/streamflow",
    download_url="".join(["https://github.com/alpha-unito/streamflow/releases"]),
    author="Iacopo Colonnelli",
    author_email="iacopo.colonnelli@unito.it",
    description="StreamFlow framework",
    long_description=long_description,
    long_description_content_type='text/markdown',
    install_requires=[
        "attrs==19.3.0",
        "bagit==1.7.0",
        "bcrypt==3.1.7",
        "cachecontrol==0.11.7",
        "cachetools==3.1.1",
        "certifi==2019.9.11",
        "cffi==1.13.2",
        "chardet==3.0.4",
        "coloredlogs==10.0",
        "cryptography==2.8",
        "cwltool==1.0.20191022103248",
        "decorator==4.4.1",
        "future==0.18.2",
        "google-auth==1.7.1",
        "humanfriendly==4.18",
        "idna==2.8",
        "importlib-metadata==0.23",
        "isodate==0.6.0",
        "jsonschema==3.2.0",
        "kubernetes==10.0.1",
        "lockfile==0.12.2",
        "lxml==4.4.2",
        "mistune==0.8.4",
        "more-itertools==7.2.0",
        "mypy-extensions==0.4.3",
        "networkx==2.4",
        "oauthlib==3.1.0",
        "paramiko==2.6.0",
        "pathlib2==2.3.5",
        "prov==1.5.1",
        "psutil==5.6.7",
        "pyasn1==0.4.8",
        "pyasn1-modules==0.2.7",
        "pycparser==2.19",
        "pynacl==1.3.0",
        "pyparsing==2.4.5",
        "pyrsistent==0.15.6",
        "python-dateutil==2.8.1",
        "pyyaml==5.1.2",
        "rdflib==4.2.2",
        "rdflib-jsonld==0.4.0",
        "requests==2.22.0",
        "requests-oauthlib==1.3.0",
        "rsa==4.0",
        "ruamel.yaml==0.16.0",
        "ruamel.yaml.clib==0.2.0",
        "scandir==1.10.0",
        "schema-salad==4.5.20191023134839",
        "scp==0.13.2",
        "setuptools",
        "shellescape==3.4.1",
        "six==1.13.0",
        "typing-extensions==3.7.4.1",
        "urllib3==1.25.7",
        "websocket-client==0.56.0",
        "wheel",
        "zipp==0.6.0",
    ],
    python_requires='>=3.7, <4',
    entry_points={"console_scripts": ["streamflow=streamflow.main"]},
    zip_safe=True,
    classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Operating System :: MacOS :: MacOS X",
        "Operating System :: POSIX",
        "Programming Language :: Python :: 3.7",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Topic :: System :: Distributed Computing",
    ],
)
