apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "streamflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamflow.labels" . | nindent 4 }}
data:
  streamflow.yml: |-
    version: v1.0
    workflows:
      {{ .Values.streamflow.workflow.name | default uuidv4 }}:
        type: {{ .Values.streamflow.workflow.type }}
        {{- if .Values.streamflow.workflow.bindings }}
        {{- with .Values.streamflow.workflow.bindings }}
        bindings:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        config:
          {{- if eq .Values.streamflow.workflow.type "cwl" }}
          file: {{ required "CWL processfile is mandatory" .Values.streamflow.workflow.cwl.processfile }}
          {{- if .Values.streamflow.workflow.cwl.jobfile }}
          settings: {{ .Values.streamflow.workflow.cwl.jobfile }}
          {{- end }}
          docker:
            - step: /
              deployment:
                type: kubernetes
                config:
                  inCluster: true
                  networkPolicy: {{ .Values.streamflow.workflow.cwl.restrictNetworkAccess }}
          {{- end }}
    {{- if .Values.streamflow.config }}
    {{- toYaml .Values.streamflow.config | nindent 4 }}
    {{- end }}