{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "streamflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamflow.labels" . | nindent 4 }}
rules:
- verbs:
    - get
    - watch
    - list
    - create
    - delete
  apiGroups:
    - ''
  resources:
    - pods
    - pods/exec
{{- if eq .Values.streamflow.workflow.type "cwl" }}
{{- if .Values.streamflow.workflow.restrictNetworkAccess }}
- verbs:
    - get
    - list
    - create
    - delete
  apiGroups:
    - networking.k8s.io
  resources:
    - networkpolicies
{{- end }}
{{- end }}
{{- end }}