apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmpi.fullname" . }}
  labels:
    {{- include "openmpi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openmpi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openmpi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: openmpi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 2022
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh-key/openmpi
      volumes:
        - name: ssh-key
          secret:
            secretName: {{ .Values.sshSecretName }}
            defaultMode: 256
